version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000" # Cambia 3000 si tu app usa otro puerto
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '2.0'      
          memory: 2048M    
    restart: unless-stopped
