version: '3.8'

services:
  app_java:
    build: .
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1536M
    restart: unless-stopped
